<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download_button</name>
   <tag></tag>
   <elementGuidId>b8bc26da-ea94-4771-b180-25d7d7625ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='downloadlink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#downloadlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3a6f46c-5a38-453c-85e6-4275832db607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anoval%3BORG%3Aglints%3BTEL%3A12345%3BURL%3Aglints.com%3BEMAIL%3Amulyanoval%40gmail.com%3BADR%3Ajakarta+indonesia%3BNOTE%3Anotesengineer%3B%3B</value>
      <webElementGuid>5cf14091-2394-469a-9a8e-7edd66bdc4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downloadlink</value>
      <webElementGuid>5b7a9edf-df32-41e5-91c9-4243a50ea9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>5de5d27a-1520-4bd5-bdab-96c667472b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downloadlink&quot;)</value>
      <webElementGuid>57ec0563-c063-41a9-943c-a2088d4b7420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='downloadlink']</value>
      <webElementGuid>0b59db5f-3241-47fe-942e-ea366d673f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downloadText']/a</value>
      <webElementGuid>48fcd289-1694-4cef-9a63-72a8d2a85309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>f44a219f-fa78-4ab5-8351-7208a6c80492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anoval%3BORG%3Aglints%3BTEL%3A12345%3BURL%3Aglints.com%3BEMAIL%3Amulyanoval%40gmail.com%3BADR%3Ajakarta+indonesia%3BNOTE%3Anotesengineer%3B%3B')]</value>
      <webElementGuid>eab17849-3241-44d4-936e-36ae4a03f5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>2bcaa527-5b79-4003-9d62-e9195dfe7c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anoval%3BORG%3Aglints%3BTEL%3A12345%3BURL%3Aglints.com%3BEMAIL%3Amulyanoval%40gmail.com%3BADR%3Ajakarta+indonesia%3BNOTE%3Anotesengineer%3B%3B' and @id = 'downloadlink' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>8c2e3beb-1aef-4eaf-b444-ea11edcf5824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
