<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Contents</name>
   <tag></tag>
   <elementGuidId>d42da0b4-7d03-4447-b174-987b42634f47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']/tbody/tr/td/table/tbody/tr/td[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.gwt-ListBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d4e5fc1-ae52-4cad-8593-5b0aa431ca7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-ListBox</value>
      <webElementGuid>37e177f3-04ff-46e7-a200-b9f78862288d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network</value>
      <webElementGuid>88648278-6a30-41d6-9f26-0e2d8c372d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;secondColumn&quot;]/select[@class=&quot;gwt-ListBox&quot;]</value>
      <webElementGuid>b1db4cb8-88e8-4398-bb1e-5515f597b500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr/td/table/tbody/tr/td[2]/select</value>
      <webElementGuid>20e8fb08-d9cb-413c-b2aa-5f705664b98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fa087afe-f117-4eb8-913f-fa8f533a8b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network' or . = 'Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network')]</value>
      <webElementGuid>0c4222ef-0b31-4067-9ecd-525233ab1214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
