<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message</name>
   <tag></tag>
   <elementGuidId>f0c8619c-0b64-45de-9e1e-1dc357166ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.gwt-TextArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2dfd6f11-3b6a-4f69-be8f-991779478419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-TextArea</value>
      <webElementGuid>59767125-e267-4e7c-9879-44f9fb9ce35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[2]/td[@class=&quot;secondColumn&quot;]/textarea[@class=&quot;gwt-TextArea&quot;]</value>
      <webElementGuid>79138701-8fd9-4cc0-862b-03c1a38376bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>fdfa61af-9f43-4a1b-9439-14f9432bbc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c38ba10d-d612-4531-90c3-6a874376ec8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
