<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download_link</name>
   <tag></tag>
   <elementGuidId>f51cd051-fe2c-40d5-9f91-aa931ac38ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlresult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#urlresult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>672c31b9-7870-4a6a-82f9-b2b00abab960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40362fea-943f-47f4-ae0d-e64963a80a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-TextBox</value>
      <webElementGuid>af9ad511-b81e-4c82-aaee-81529f8d7ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlresult</value>
      <webElementGuid>938b434c-7952-41b7-a178-4f8552b3e3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlresult&quot;)</value>
      <webElementGuid>8d187672-f1bc-4e2a-9a11-f3b3ae18d938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlresult']</value>
      <webElementGuid>cb0feaf2-4ae9-40e6-b620-cafd786a24af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mainpanel']/tbody/tr/td[2]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>08107cc4-1e9a-4bb7-96a0-09db7ea8ad97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>c48d5d85-c623-4b56-8c71-11211c6c786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'urlresult']</value>
      <webElementGuid>1e3f4dc6-7f99-4e45-adb8-8e746b3097eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
