<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textbox_Memo</name>
   <tag></tag>
   <elementGuidId>f6e27f32-7bfa-4588-9121-e2d25fc4fc0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(9) > td.secondColumn > input.gwt-TextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca12a45-cb47-4e36-ac4c-605c5b1d2fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>301702eb-9b5a-468c-8093-1df422f6cd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-TextBox</value>
      <webElementGuid>e25ebce9-bf3d-46e1-b08d-a78fe2eef6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[9]/td[@class=&quot;secondColumn&quot;]/input[@class=&quot;gwt-TextBox&quot;]</value>
      <webElementGuid>ff299c44-4f71-451c-91f5-75d86e6e2faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>88582d75-7226-4bb2-98bd-faf3ab2ae48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>0c8f3560-049f-46cb-a8ea-e796b64e6f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/input</value>
      <webElementGuid>df0cd8e7-e041-412d-a475-a722ea026ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>3f611eb6-c9a9-4f26-aeae-209600fab1dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
