<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Contents</name>
   <tag></tag>
   <elementGuidId>07591517-739f-4d59-b755-1c2dfb3d3c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']/tbody/tr/td/table/tbody/tr/td[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.gwt-ListBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c709db0-5e0d-41cd-ab1e-f28c45664dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-ListBox</value>
      <webElementGuid>19c3453f-f5a4-49ad-8c3e-7455d05d2887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network</value>
      <webElementGuid>5f6c4bc6-697f-4297-aae6-44f47a154046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;secondColumn&quot;]/select[@class=&quot;gwt-ListBox&quot;]</value>
      <webElementGuid>fad9d048-e22d-4e1b-9bd3-0dd9c805e26a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr/td/table/tbody/tr/td[2]/select</value>
      <webElementGuid>bbb5e122-b490-4f8f-a08b-5a1685765654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a87f2634-72dc-49fd-b3f3-7a10cb3a5a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network' or . = 'Calendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi network')]</value>
      <webElementGuid>90831d93-4171-4cbc-ad9b-c710db1adfde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
