<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>191863ab-1a49-43d7-a947-96b7b23e4882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='downloadlink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#downloadlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d96aa30-77a1-436e-ba9a-cd4e2c24827a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=BEGIN%3AVEVENT%0D%0ASUMMARY%3Aglints%0D%0ADTSTART%3BVALUE%3DDATE%3A20241222%0D%0ADTEND%3BVALUE%3DDATE%3A20241223%0D%0ALOCATION%3Ajakart%0D%0ADESCRIPTION%3Ainterview%0D%0AEND%3AVEVENT%0D%0A</value>
      <webElementGuid>405b3166-e5d7-4f38-902d-f68c4709e87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downloadlink</value>
      <webElementGuid>a494b9b6-1ccc-4005-a7c2-f1ff24ee1e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>521044df-310e-4690-855a-eb2ab19b12c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downloadlink&quot;)</value>
      <webElementGuid>4f7ba6de-2248-4dfd-b0ff-708aaa50cf8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='downloadlink']</value>
      <webElementGuid>ddf8a11d-4bf1-40a1-95fe-c99e72e92d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downloadText']/a</value>
      <webElementGuid>4d5f2d9b-da36-4894-8859-151758845734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>60779f81-7c5b-4264-a29c-60b771b5429f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=BEGIN%3AVEVENT%0D%0ASUMMARY%3Aglints%0D%0ADTSTART%3BVALUE%3DDATE%3A20241222%0D%0ADTEND%3BVALUE%3DDATE%3A20241223%0D%0ALOCATION%3Ajakart%0D%0ADESCRIPTION%3Ainterview%0D%0AEND%3AVEVENT%0D%0A')]</value>
      <webElementGuid>1a44c581-42a2-489e-a109-bb5508c94763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>4d80a831-ad48-44b9-9f0b-6aa945bf2e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=BEGIN%3AVEVENT%0D%0ASUMMARY%3Aglints%0D%0ADTSTART%3BVALUE%3DDATE%3A20241222%0D%0ADTEND%3BVALUE%3DDATE%3A20241223%0D%0ALOCATION%3Ajakart%0D%0ADESCRIPTION%3Ainterview%0D%0AEND%3AVEVENT%0D%0A' and @id = 'downloadlink' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>d4967cf7-d48f-42ff-8e70-a79ca3475f58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
