<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endDate_22</name>
   <tag></tag>
   <elementGuidId>fe0da428-9d63-4d27-a841-25dde15baac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[5]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.datePickerDay.datePickerDayIsWeekend.datePickerDayIsToday.datePickerDayIsValue.datePickerDayIsHighlighted.datePickerDayIsValueAndHighlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0866070-c770-48e1-9c99-ede422d7f50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa5e369c-810f-4a79-a9b4-a18d16fb5721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4f3bacb6-16f5-4c5e-9115-06224cc0a7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePickerDay datePickerDayIsWeekend datePickerDayIsToday datePickerDayIsValue  datePickerDayIsHighlighted datePickerDayIsValueAndHighlighted</value>
      <webElementGuid>75aa31b1-a993-40f0-b714-3562f8a16d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>3b11869d-3c3d-4acc-a08a-8651477483e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[5]/td[@class=&quot;secondColumn&quot;]/table[@class=&quot;gwt-DatePicker&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;datePickerDays&quot;]/tbody[1]/tr[5]/td[7]/div[@class=&quot;datePickerDay datePickerDayIsWeekend datePickerDayIsToday datePickerDayIsValue  datePickerDayIsHighlighted datePickerDayIsValueAndHighlighted&quot;]</value>
      <webElementGuid>75e39e2c-1179-4a3b-bfa1-8aa2478780f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[5]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td[7]/div</value>
      <webElementGuid>3a073517-b9ab-4623-b67a-aa5b6a35c9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td[7]/div</value>
      <webElementGuid>301a8c52-ee84-45e3-8c6b-1723be102e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '22' or . = '22')]</value>
      <webElementGuid>dd4bb56e-cd63-48d7-a8f0-e6338a934460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
