<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>startDate_22</name>
   <tag></tag>
   <elementGuidId>25da94c5-250a-4141-882f-a82e036dc733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[3]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.datePickerDay.datePickerDayIsWeekend.datePickerDayIsToday.datePickerDayIsValue.datePickerDayIsHighlighted.datePickerDayIsValueAndHighlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b616618a-4be1-4d53-9dc4-f4555fa50137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd6ce0c9-cfa3-49e1-8ca3-72ed7264ba5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc9e0698-1184-4a6a-bc1e-c0904cd8f889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePickerDay datePickerDayIsWeekend datePickerDayIsToday datePickerDayIsValue  datePickerDayIsHighlighted datePickerDayIsValueAndHighlighted</value>
      <webElementGuid>903817ed-2610-446f-9a03-7f2ee2ce12db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>d8bd8366-d8a6-4ba1-a0ee-9d8c1eb927a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[@class=&quot;secondColumn&quot;]/table[@class=&quot;gwt-DatePicker&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;datePickerDays&quot;]/tbody[1]/tr[5]/td[7]/div[@class=&quot;datePickerDay datePickerDayIsWeekend datePickerDayIsToday datePickerDayIsValue  datePickerDayIsHighlighted datePickerDayIsValueAndHighlighted&quot;]</value>
      <webElementGuid>07b30424-e374-4c3c-ad68-4451c62ace22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[2]/td/table/tbody/tr[3]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td[7]/div</value>
      <webElementGuid>acdac840-2d22-477a-8107-9450a66dc2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[7]/div</value>
      <webElementGuid>f5fda74d-c9c4-49ad-ae68-4c8fe0328720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '22' or . = '22')]</value>
      <webElementGuid>af585e89-d1dc-4d6c-868c-bd0bc272e527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
