<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Decoded_filled</name>
   <tag></tag>
   <elementGuidId>189b1509-57c8-45de-9d11-5f731c8fefaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='decoded']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#decoded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4771d02c-1386-4d24-9489-6d96e2127a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decoded</value>
      <webElementGuid>602be49a-66fc-4f88-9f0a-1a28ccd3ff1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>91866bbe-7281-44cb-a86c-851fc4570f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>25a2d941-aa50-4696-bdc7-f02a43b29fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MECARD:N:Mulya Noval Nugraha;ORG:Glints;TEL:12345678;URL:glints.com;EMAIL:mulyanoval@gmail.com;ADR:Jakarta Indonesia;NOTE:MemoQA Engineer;;</value>
      <webElementGuid>5a7b8cd8-aa68-40db-8889-abd8518bcf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decoded&quot;)</value>
      <webElementGuid>3af2a317-62a2-4c9b-b31e-04cac668de7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='decoded']</value>
      <webElementGuid>34db316d-4db4-49d5-b6e4-c2007eda3ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d3113021-bb13-461b-bddf-47182bd32ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'decoded' and (text() = 'MECARD:N:Mulya Noval Nugraha;ORG:Glints;TEL:12345678;URL:glints.com;EMAIL:mulyanoval@gmail.com;ADR:Jakarta Indonesia;NOTE:MemoQA Engineer;;' or . = 'MECARD:N:Mulya Noval Nugraha;ORG:Glints;TEL:12345678;URL:glints.com;EMAIL:mulyanoval@gmail.com;ADR:Jakarta Indonesia;NOTE:MemoQA Engineer;;')]</value>
      <webElementGuid>9ee08738-34d7-4d8b-9955-76ab0513cc09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
